### ISSUE TITLE
Text doesn't inject properly

### ISSUE THREAD

**Issue by 8enmann** [JasonBenn/duet#1]
<img width="289" alt="Screen Shot 2019-05-14 at 12 00 04 PM" src="https://user-images.githubusercontent.com/1021104/57724545-e21bca00-763f-11e9-804b-2bbd2147ed55.png">

**Comment by naianaia** [comment]
Added broader event handler but didn't change logic. Seems to be working now

**Comment by naianaia** [comment]
Still flaky behavior. need to look into more deeply

**Comment by naianaia** [comment]
addOnlyAtEnd makes this moot.
