### ISSUE TITLE
js stripping preceding space when appending text from generator

### ISSUE THREAD

**Issue by 8enmann** [JasonBenn/duet#9]
"I ate a delicious"
<img width="543" alt="Screen Shot 2019-05-15 at 3 05 21 PM" src="https://user-images.githubusercontent.com/1021104/57812775-e5d44d00-7722-11e9-9670-94a0023a2064.png">

**Comment by naianaia** [comment]
fixt

**Comment by 8enmann** [comment]
I saw a case where the model generated "," as the first token and it inserted an extra space

**Comment by naianaia** [comment]
@8enmann  screenshot?

**Comment by 8enmann** [comment]
Anything where the model generates a comma as the first token. Why are you
prepending space in js?

**Comment by naianaia** [comment]
seemed like the most direct way, lol. will fix tmr

**Comment by naianaia** [comment]
Working now but hack-y. Feel free to improve.
